# Generated by Django 5.0.6 on 2024-05-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servicio', models.IntegerField()),
                ('nombre_servicio', models.CharField(max_length=200)),
                ('descripcion_servicio', models.CharField(max_length=1000)),
                ('costo_servicio', models.IntegerField()),
            ],
        ),
    ]
