# Generated by Django 5.0.6 on 2024-05-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='id_servicio',
        ),
    ]
