# Generated by Django 5.0.6 on 2024-05-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
