# Generated by Django 5.0.6 on 2024-05-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='pagina_servicio',
            field=models.CharField(default='/servicios/tipo/electrico/', max_length=500),
            preserve_default=False,
        ),
    ]
