# Generated by Django 5.0.6 on 2024-05-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.TextField(max_length=1000),
        ),
    ]
