# Generated by Django 5.0.6 on 2024-05-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_servicio_descripcion_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen_servicio',
            field=models.ImageField(blank=True, null=True, upload_to='servicios'),
        ),
    ]
