# Generated by Django 5.0.6 on 2024-05-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_servicio_imagen_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo_servicio',
            field=models.CharField(max_length=100),
        ),
    ]
