# Generated by Django 5.0.6 on 2024-05-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_empleado_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_mecanico',
            field=models.CharField(choices=[('---', '---'), ('general', 'general'), ('electrico', 'Electrico'), ('motriz', 'motriz'), ('frenos', 'frenos')], default='---', max_length=20),
        ),
    ]
